### ISSUE TITLE
CMAKE_CXX_STANDARD

### ISSUE THREAD

**Issue by zichunxx** [PinocchioYS/realtime_occupancy_mapping#2]
Hi! @PinocchioYS 

I've been trying to `catkin build` this repo and met some PCL-ros-related issues. 

By default, `CMakeList` does not explicitly specify the version of C++. 

However, `set(CMAKE_CXX_STANDARD 14)` will make the build process go fine. 

Is it the right way to be adopted when building this repo on Ubuntu 20.04?

Thanks.

**Comment by PinocchioYS** [comment]
Hi,

As I know, Ubuntu 20.04 uses C++ 14 as the default CMAKE_CXX_STANDARD.
So your solution works well in setting, i.e., Ubuntu 20.04.

I removed the lines in CMakeList.txt to support the other development environment.

Now, this project uses a default version of C++ compiler.

Thanks for this issue!
